# For use with local development only.
# From postgres Docker README: https://github.com/docker-library/docs/blob/master/postgres/README.md#-via-docker-compose
services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
  test-db-ephemeral:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
  go-test-db:
    image: golang
    depends_on:
      test-db-ephemeral:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PGHOST: test-db-ephemeral
      PGPORT: "5433"
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: billing
    command: ["bash", "-lc", "make test-db-ci"]
