// dbtx contains the [Querier] and [Queries] types, which are maintained manually. The contents of the [db] package are generated by sqlc and regularly overwritten, making it unsuitable for custom code.
package dbtx

import (
	"github.com/jackc/pgx/v5"

	"github.com/cloud-gov/billing/internal/db"
)

// Querier extends the [db.Querier] interface with support for transactions. This addresses an issue in sqlc in which the WithTx method is not included in the Querier interface definition. Solution source: https://github.com/sqlc-dev/sqlc/issues/383#issuecomment-613083090
type Querier interface {
	db.Querier
	WithTx(tx pgx.Tx) Querier
}

type Queries struct {
	*db.Queries
}

func (q *Queries) WithTx(tx pgx.Tx) Querier {
	return &Queries{
		Queries: q.Queries.WithTx(tx),
	}
}

func NewQuerier(q *db.Queries) Querier {
	return &Queries{
		Queries: q,
	}
}
