// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type CfOrg struct {
	ID           interface{}
	Name         string
	TierID       string
	CreditsQuota int64
	CreditsUsed  int64
	CustomerID   int64
}

type Customer struct {
	ID   int64
	Name string
}

type Tier struct {
	ID          int32
	Name        string
	TierCredits sql.NullInt64
}
