// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type BillableClass struct {
	ID            int32
	NativeID      sql.NullString
	Credits       sql.NullInt32
	Amount        sql.NullInt32
	UnitOfMeasure string
}

type BillableResource struct {
	ID       int32
	NativeID sql.NullString
	ClassID  sql.NullInt32
	CfOrgID  uuid.NullUUID
}

type CfOrg struct {
	ID           uuid.UUID
	Name         string
	TierID       int32
	CreditsQuota int64
	CreditsUsed  int64
	CustomerID   int64
}

type Customer struct {
	ID   int64
	Name string
}

type Tier struct {
	ID          int32
	Name        string
	TierCredits sql.NullInt64
}
