// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package db

import (
	"context"
)

const getAccountForCustomerAndType = `-- name: GetAccountForCustomerAndType :one
SELECT a.id, a.customer_id, a.type
FROM account a
JOIN customer c on a.customer_id = c.id
WHERE c.name = $1
AND a.type = $2
LIMIT 1
`

type GetAccountForCustomerAndTypeParams struct {
	Name string
	Type int32
}

func (q *Queries) GetAccountForCustomerAndType(ctx context.Context, arg GetAccountForCustomerAndTypeParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForCustomerAndType, arg.Name, arg.Type)
	var i Account
	err := row.Scan(&i.ID, &i.CustomerID, &i.Type)
	return i, err
}
