// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateMeasurements implements pgx.CopyFromSource.
type iteratorForCreateMeasurements struct {
	rows                 []CreateMeasurementsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMeasurements) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMeasurements) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ReadingID,
		r.rows[0].Meter,
		r.rows[0].ResourceNaturalID,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForCreateMeasurements) Err() error {
	return nil
}

func (q *Queries) CreateMeasurements(ctx context.Context, arg []CreateMeasurementsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"measurement"}, []string{"reading_id", "meter", "resource_natural_id", "value"}, &iteratorForCreateMeasurements{rows: arg})
}
