// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: measurement.sql

package db

type CreateMeasurementsParams struct {
	ReadingID  int32
	ResourceID int32
	Value      int32
}
