// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CFOrg struct {
	ID           pgtype.UUID
	Name         pgtype.Text
	TierID       pgtype.Int4
	CreditsQuota pgtype.Int8
	CreditsUsed  pgtype.Int8
	CustomerID   pgtype.Int8
}

type Customer struct {
	ID   int64
	Name string
}

type Measurement struct {
	ReadingID         int32
	Meter             string
	ResourceNaturalID string
	Value             int32
}

// A Meter reads usage information from a system in Cloud.gov. It also namespaces natural IDs for resources and resource_kinds; meter + natural_id is a primary key.
type Meter struct {
	Name string
}

type Reading struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	// Periodic is true if a reading was taken automatically as part of the periodic usage measurement schedule, or false if it was requested manually.
	Periodic bool
}

type Resource struct {
	Meter         string
	NaturalID     string
	KindNaturalID string
	CFOrgID       pgtype.UUID
}

// ResourceKind represents a particular kind of billable resource. Note that natural_id can be empty because some meters may only read one kind of resource, and that resource kind may not have a unique identifier in the target system; it is uniquely identified by the meter name only.
type ResourceKind struct {
	Meter         string
	NaturalID     string
	Credits       pgtype.Int4
	Amount        pgtype.Int4
	UnitOfMeasure pgtype.Text
}

type Tier struct {
	ID          int32
	Name        string
	TierCredits int64
}

type Transaction struct {
	ID                int32
	TransactionDate   pgtype.Date
	CFOrgID           pgtype.UUID
	Description       pgtype.Text
	Direction         pgtype.Int4
	Amount            int32
	TransactionTypeID int32
}

type TransactionType struct {
	ID   int32
	Name string
}
