// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CFOrg struct {
	ID           pgtype.UUID
	Name         string
	TierID       int32
	CreditsQuota int64
	CreditsUsed  int64
	CustomerID   int64
}

type Customer struct {
	ID   int64
	Name string
}

type Measurement struct {
	ReadingID  int32
	ResourceID int32
	Value      int32
}

type Meter struct {
	Name string
}

type Reading struct {
	ID        int32
	CreatedAt pgtype.Timestamp
}

type Resource struct {
	ID            int32
	NaturalID     string
	Meter         string
	KindNaturalID pgtype.Text
	CFOrgID       pgtype.UUID
}

type ResourceKind struct {
	Meter         string
	NaturalID     string
	Credits       pgtype.Int4
	Amount        pgtype.Int4
	UnitOfMeasure string
}

type Tier struct {
	ID          int32
	Name        string
	TierCredits int64
}
