// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reading.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReading = `-- name: CreateReading :one
INSERT INTO reading (
	created_at
) VALUES (
	$1
)
RETURNING id, created_at
`

func (q *Queries) CreateReading(ctx context.Context, createdAt pgtype.Timestamp) (Reading, error) {
	row := q.db.QueryRow(ctx, createReading, createdAt)
	var i Reading
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
