// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resource_node.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateResourceNodes = `-- name: BulkCreateResourceNodes :exec
insert into resource_node (customer_id, slug, path, resource_natural_id)
select distinct on (rn.customer_id, rn.slug) customer_id, slug, path, resource_natural_id
from
  unnest(
    $1::uuid[],
    $2::text[],
    $3::ltree[],
    $4::text[]
  ) as rn (customer_id, slug, path, resource_natural_id)
on conflict (customer_id, slug) do nothing
`

type BulkCreateResourceNodesParams struct {
	CustomerID        []pgtype.UUID
	Slug              []string
	Path              []string
	ResourceNaturalID []string
}

// BulkCreateResourcesNodes creates Resource_Node rows in bulk with the minimum required columns. If a row with the given primary key already exists, that input item is ignored.
func (q *Queries) BulkCreateResourceNodes(ctx context.Context, arg BulkCreateResourceNodesParams) error {
	_, err := q.db.Exec(ctx, bulkCreateResourceNodes,
		arg.CustomerID,
		arg.Slug,
		arg.Path,
		arg.ResourceNaturalID,
	)
	return err
}

const getResourceNode = `-- name: GetResourceNode :one
/*
We can have ambiguous columns because sqlc handles it
noqa: disable=AM04
*/

select path, slug, customer_id, resource_natural_id from resource_node
where customer_id = $1 and slug = $2
`

type GetResourceNodeParams struct {
	CustomerID pgtype.UUID
	Slug       string
}

func (q *Queries) GetResourceNode(ctx context.Context, arg GetResourceNodeParams) (ResourceNode, error) {
	row := q.db.QueryRow(ctx, getResourceNode, arg.CustomerID, arg.Slug)
	var i ResourceNode
	err := row.Scan(
		&i.Path,
		&i.Slug,
		&i.CustomerID,
		&i.ResourceNaturalID,
	)
	return i, err
}

const listAncestors = `-- name: ListAncestors :many
select path, slug, customer_id, resource_natural_id from resource_node
where path @> subpath($1::ltree, -1)
`

func (q *Queries) ListAncestors(ctx context.Context, path string) ([]ResourceNode, error) {
	rows, err := q.db.Query(ctx, listAncestors, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceNode
	for rows.Next() {
		var i ResourceNode
		if err := rows.Scan(
			&i.Path,
			&i.Slug,
			&i.CustomerID,
			&i.ResourceNaturalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescendants = `-- name: ListDescendants :many
select path, slug, customer_id, resource_natural_id from resource_node
where subpath(path, -1) <@ $1::ltree
`

func (q *Queries) ListDescendants(ctx context.Context, path string) ([]ResourceNode, error) {
	rows, err := q.db.Query(ctx, listDescendants, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceNode
	for rows.Next() {
		var i ResourceNode
		if err := rows.Scan(
			&i.Path,
			&i.Slug,
			&i.CustomerID,
			&i.ResourceNaturalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
