// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resource_node.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateResourceNodes = `-- name: BulkCreateResourceNodes :exec
insert into resource_node (customer_id, slug, path, resource_natural_id)
select distinct on (rn.customer_id, rn.slug) customer_id, slug, path, resource_natural_id
from
  unnest(
    $1::uuid[],
    $2::text[],
    $3::ltree[],
    $4::text[]
  ) as rn (customer_id, slug, path, resource_natural_id)
on conflict (customer_id, resource_natural_id) do update
  set slug = excluded.slug, path = excluded.path
`

type BulkCreateResourceNodesParams struct {
	CustomerID        []pgtype.UUID
	Slug              []string
	Path              []string
	ResourceNaturalID []string
}

// BulkCreateResourcesNodes creates Resource_Node rows in bulk with the minimum required columns. If a row with the given primary key already exists, that input item is ignored.
func (q *Queries) BulkCreateResourceNodes(ctx context.Context, arg BulkCreateResourceNodesParams) error {
	_, err := q.db.Exec(ctx, bulkCreateResourceNodes,
		arg.CustomerID,
		arg.Slug,
		arg.Path,
		arg.ResourceNaturalID,
	)
	return err
}

const getAppsUsageBySpace = `-- name: GetAppsUsageBySpace :many
select
  subpath(rn.path, 1, -2) as org,
  regexp_replace(
    subpath(rn.path, 1, -1)::text,
    '_?(test|dev|stage|staging|prod)$', -- to aggregate environments
    ''
  ) as space,
  sum(m.amount_microcredits) as total_microcredits,
  sum(m.amount_microcredits) / 1000000 as total_credits
from resource_node as rn
  inner join measurement as m on rn.resource_natural_id = m.resource_natural_id
where
  rn.customer_id = $1
  and rn.path ~ 'apps.usage.cforg%.space%.*{1,}'
group by org, space
`

type GetAppsUsageBySpaceRow struct {
	Org               string
	Space             string
	TotalMicrocredits pgtype.Numeric
	TotalCredits      pgtype.Numeric
}

func (q *Queries) GetAppsUsageBySpace(ctx context.Context, customerID pgtype.UUID) ([]GetAppsUsageBySpaceRow, error) {
	rows, err := q.db.Query(ctx, getAppsUsageBySpace, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppsUsageBySpaceRow
	for rows.Next() {
		var i GetAppsUsageBySpaceRow
		if err := rows.Scan(
			&i.Org,
			&i.Space,
			&i.TotalMicrocredits,
			&i.TotalCredits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceNode = `-- name: GetResourceNode :one
/*
We can have ambiguous columns because sqlc handles it
noqa: disable=AM04
*/

select path, slug, customer_id, resource_natural_id from resource_node
where customer_id = $1 and slug = $2
`

type GetResourceNodeParams struct {
	CustomerID pgtype.UUID
	Slug       pgtype.Text
}

func (q *Queries) GetResourceNode(ctx context.Context, arg GetResourceNodeParams) (ResourceNode, error) {
	row := q.db.QueryRow(ctx, getResourceNode, arg.CustomerID, arg.Slug)
	var i ResourceNode
	err := row.Scan(
		&i.Path,
		&i.Slug,
		&i.CustomerID,
		&i.ResourceNaturalID,
	)
	return i, err
}

const getUsageByPath = `-- name: GetUsageByPath :many
select
  coalesce(subltree(rn.path, 2, 3)::text, '') as l1,
  coalesce(regexp_replace(
    subltree(rn.path, 3, 4)::text,
    '^(.*)_.*$', -- to aggregate environments
    '\1'
  )::text, '') as l2,
  coalesce(subpath(rn.path, 3, -1)::text, '') as l3,
  coalesce(subpath(rn.path, 4)::text, '') as l4,
  sum(m.amount_microcredits) as total_microcredits,
  round(sum(m.amount_microcredits) * 1e-6, 3) as total_credits,
  round(sum(m.amount_microcredits) * 1e-6 * 50, 2) as total_cost
from resource_node as rn
  inner join measurement as m on rn.resource_natural_id = m.resource_natural_id
where
  rn.customer_id = $1
  and rn.path ~ $2::lquery
group by rollup (l1, l2, l3, l4)
order by l1
`

type GetUsageByPathParams struct {
	CustomerID pgtype.UUID
	Path       string
}

type GetUsageByPathRow struct {
	L1                pgtype.Text
	L2                pgtype.Text
	L3                pgtype.Text
	L4                pgtype.Text
	TotalMicrocredits pgtype.Numeric
	TotalCredits      pgtype.Numeric
	TotalCost         pgtype.Numeric
}

func (q *Queries) GetUsageByPath(ctx context.Context, arg GetUsageByPathParams) ([]GetUsageByPathRow, error) {
	rows, err := q.db.Query(ctx, getUsageByPath, arg.CustomerID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageByPathRow
	for rows.Next() {
		var i GetUsageByPathRow
		if err := rows.Scan(
			&i.L1,
			&i.L2,
			&i.L3,
			&i.L4,
			&i.TotalMicrocredits,
			&i.TotalCredits,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lQueryResourceNodes = `-- name: LQueryResourceNodes :many
select path, slug, customer_id, resource_natural_id from resource_node
where customer_id = $1 and path ~ $2::lquery
`

type LQueryResourceNodesParams struct {
	CustomerID pgtype.UUID
	Path       string
}

func (q *Queries) LQueryResourceNodes(ctx context.Context, arg LQueryResourceNodesParams) ([]ResourceNode, error) {
	rows, err := q.db.Query(ctx, lQueryResourceNodes, arg.CustomerID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceNode
	for rows.Next() {
		var i ResourceNode
		if err := rows.Scan(
			&i.Path,
			&i.Slug,
			&i.CustomerID,
			&i.ResourceNaturalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceNodeAncestors = `-- name: ListResourceNodeAncestors :many
select path, slug, customer_id, resource_natural_id from resource_node
where path @> subpath($1::ltree, -1)
`

func (q *Queries) ListResourceNodeAncestors(ctx context.Context, path string) ([]ResourceNode, error) {
	rows, err := q.db.Query(ctx, listResourceNodeAncestors, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceNode
	for rows.Next() {
		var i ResourceNode
		if err := rows.Scan(
			&i.Path,
			&i.Slug,
			&i.CustomerID,
			&i.ResourceNaturalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceNodeDescendants = `-- name: ListResourceNodeDescendants :many
select path, slug, customer_id, resource_natural_id from resource_node
where subpath(path, -1) <@ $1::ltree
`

func (q *Queries) ListResourceNodeDescendants(ctx context.Context, path string) ([]ResourceNode, error) {
	rows, err := q.db.Query(ctx, listResourceNodeDescendants, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceNode
	for rows.Next() {
		var i ResourceNode
		if err := rows.Scan(
			&i.Path,
			&i.Slug,
			&i.CustomerID,
			&i.ResourceNaturalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
